INSERT INTO PERSONNES VALUES ((SELECT MAX(NUMERO)+1 FROM PERSONNES),'Zeinalov', 'Dmitrii', 
    'St-Blaise', 2000, 'Neuch', '078247', '2004-06-23', 'H', 'assurance', 'bleu', 'Russe');

--1
UPDATE PERSONNES SET TELEPHONE = '0782476065' WHERE NOM ILIKE 'ZEINALOV';

--2
DELETE FROM PERSONNES WHERE NOM ILIKE 'ZEINALOV';

--3
UPDATE PERSONNES SET PROVINCE = 'TERRE-NEUVE' WHERE VILLE ILIKE 'MONTREAL' AND PROVINCE = 'QUEBEC'; 

--4
DELETE FROM PERSONNES WHERE DATE_NAISSANCE < '1950-12-31';

--5
SELECT NOM, PRENOM, ASSURANCE_SOCIALE
FROM PERSONNES
WHERE ASSURANCE_SOCIALE ILIKE '%432%';

--6
SELECT NOM, COULEUR_YEUX, LANGUE, PROVINCE
FROM PERSONNES
WHERE PROVINCE ILIKE 'QUEBEC'
AND (COULEUR_YEUX = 'BLEU' AND LANGUE ILIKE 'FRANCAIS')
OR (COULEUR_YEUX = 'BRUN' AND LANGUE ILIKE 'ANGLAIS');

--7
SELECT NOM, PRENOM 
FROM PERSONNES
WHERE PRENOM ILIKE 'S%';

--8
SELECT NOM, PRENOM 
FROM PERSONNES
ORDER BY NOM, PRENOM ASC;

--9
SELECT NOM, PRENOM 
FROM PERSONNES
WHERE LANGUE ILIKE 'ESPAGNOL';

--10
SELECT NOM, PRENOM, DATE_NAISSANCE 
FROM PERSONNES
WHERE PROVINCE ILIKE 'QUEBEC'
AND (COULEUR_YEUX ILIKE 'BLEU' OR COULEUR_YEUX ILIKE 'VERT');

--11
SELECT NOM, PRENOM, CODE_POSTAL, VILLE
FROM PERSONNES
WHERE CODE_POSTAL ILIKE 'G_____1%';

--12. Création table proffessions
CREATE TABLE PROFESSIONS (CODE INTEGER PRIMARY KEY, LIBELLE VARCHAR(40), SALAIRE_HORAIRE NUMERIC(9,2));

--12. Modification structure table Personnes
ALTER TABLE PERSONNES ADD FK1_PERSONNES_PROFESSION INTEGER;

--13 INSERT INTO PROFESSEURS
INSERT INTO PROFESSIONS (CODE, LIBELLE, SALAIRE_HORAIRE)
VALUES (100, 'INGENIEUR', 110),
(110, 'TECHNICIEN', 25),
(120, 'INFORMATICIEN', 80),
(130, 'CUISINIER', 110),
(140, 'SECRETAIRE', 50),
(150, 'TELEPHONISTE', 90),
(160, 'CAISSIER', 90),
(170, 'MANAGER', 150);

--14 UPDATE PERSONNES
UPDATE PERSONNES SET FK1_PERSONNES_PROFESSION = 100 WHERE VILLE = 'BAIE-COMEAU';
UPDATE PERSONNES SET FK1_PERSONNES_PROFESSION = 110 WHERE VILLE = 'GASPE';
UPDATE PERSONNES SET FK1_PERSONNES_PROFESSION = 120 WHERE VILLE = 'LA MALBAIE';
UPDATE PERSONNES SET FK1_PERSONNES_PROFESSION = 130 WHERE VILLE = 'MONTREAL';
UPDATE PERSONNES SET FK1_PERSONNES_PROFESSION = 140 WHERE VILLE = 'OTTAWA';
UPDATE PERSONNES SET FK1_PERSONNES_PROFESSION = 150 WHERE VILLE = 'QUEBEC';
UPDATE PERSONNES SET FK1_PERSONNES_PROFESSION = 160 WHERE VILLE = 'REVIERE-DU-LOUP';
UPDATE PERSONNES SET FK1_PERSONNES_PROFESSION = 170 WHERE VILLE = 'SEPT-ILES';

--15 
SELECT PROFESSEURS.NOM, PROFESSION.NOM
FROM PERSONNES
INNER JOIN PROFESSION ON (PERSONNES.FK1_PERSONNES_PROFESSION = PROFESSION.NUMERO)